version: "3.0"

services:
    backend:
        command: ./mvnw -B clean spring-boot:run
        ports: []
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend_router.rule=Host(`api.nspain.me`)"
            - "traefik.http.routers.backend_router.entryPoints=websecure"
            - "traefik.http.routers.backend_router.tls.certresolver=myhttpchallenge"
            - "traefik.http.routers.backend_router.tls"
            - "traefik.http.routers.backend_router.service=backend_service"
            - "traefik.http.services.backend_service.loadbalancer.server.port=8080"
            - "traefik.docker.network=traefik"
        networks:
            - traefik

networks:
   traefik:
       external: true        
