version: 2

jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            docker pull openjdk:8-jdk-slim | grep -e 'Pulling from' -e 'Digest' -e 'Status' -e 'Error'
            docker run --rm -v $PWD:/opt/maven -w /opt/maven openjdk:8-jdk-slim \
                ./mvnw -B antrun:run@ktlint | grep -E -v "Download(ing|ed)"
      - run:
          name: Test
          command: |
            docker-compose pull >/dev/null
            docker-compose -f docker-compose.yml -f docker-compose.test.yml up \
                --abort-on-container-exit --exit-code-from backend | grep -E -v "Download(ing|ed)"
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
