version: 2

jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout

      - run:
          name: Lint
          command: docker run --rm -v $PWD:/opt/maven -w /opt/maven openjdk:8-jdk-slim ./mvnw antrun:run@ktlint

      - run:
          name: Test
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from backend